/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Place = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'aliases' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Place = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'aliases' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };